name: SQL Schema Code Linter

on:
  push:
    branches: [ laboratory-work-4 ] 

jobs:
  SQLLinter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code in Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install SQLFluff
        run: pip install sqlfluff # Прямий виклик pip зазвичай працює після setup-python
        
      - name: Start SQL Linter (Check Modified Schema)
        run: |
          # Перевіряємо модифікований файл
          sqlfluff lint .github/workflows/DataSchemaModified.sql --dialect postgres
