name: Print Software Versions Check 

on:
  push:
    branches: [ laboratory-work-4 ] 

jobs:
  PrintLanguageVersions:
    name: Check BL/Java Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Print Java Version
        run: java -version
        
  PrintDBMSVersions:
    name: Check AL/PostgreSQL Version
    runs-on: ubuntu-latest
    needs: [PrintLanguageVersions]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Setup PostgreSQL Client
        run: |
          # Встановлення PostgreSQL клієнта для перевірки версії
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Print PostgreSQL Version
        run: psql --version
